### PR TITLE
Fix the Docker build, which is broken by missing S3 buckets

### LINKED ISSUE #214: Uncaught errors print the full source of zstd-codec-binding-wasm
This is very weird, but 100% reproducible for me on all active Node versions. Any clues welcome!

Repro:
* Create an empty folder
* `npm install zstd-codec`
* Create a `test.js` file containing:
  ```javascript
  const { ZstdCodec } = require('zstd-codec');

  ZstdCodec.run(() => {
      console.log('Zstd loaded');

      setImmediate(() => {
          throw new Error('test error');
      });
  });
  ```
* `node test.js`

This code fails immediately, due to an uncaught exception, but just before it does it prints the entirety of the contents of `zstd-codec-binding-wasm.js` to stderr. It's a huge amount of output, which makes debugging errors (especially failing tests) in any codebase that uses zstd-codec very difficult.

Any idea why this might be happening?

### PR DESCRIPTION
**Pull request by pimterry**
Hi @yoshihitoh. I'm trying to fix #214, but first I need to be able to build zstd here. The current build was broken, primarily because https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz is no longer available, and that's apparently not how you're supposed to use emsdk anymore.

I've had a go at fixing this. This PR changes the Dockerfile to one that does work, using the emsdk docker image as a base, and the closest EMCC version that was available (according to `emsdk list`).

This builds successfully, which is great! Unfortunately, the resulting build doesn't quite work though. When I run `npm run build-binding` it builds & updates the binding successfully, but then the JS tests fail with various "offset is out of bounds" errors.

Any idea what might cause this? I'd love to go further and set the flags to fix #214, but I'm a bit stuck at this point.

### CODE REVIEW

**Comment by yoshihitoh** [comment]
Hi @pimterry, thank you for reporting an issue, and trying to fix it by yourself!

> but then the JS tests fail with various "offset is out of bounds" errors.

Since this module is using an old Emscripten version, maybe there are several important changes that this module should follow. I think this error is produced by interoperations between JS and C++ code. I'll investigate it next weekend.

**Comment by pimterry** [comment]
Ok, thanks @yoshihitoh!

Do let me know if there's anything I can look into to help. I'm not really sure how to continue from here to investigate those interoperation issues, but I'm happy to get more involved if there's anything you can suggest I should look into to help get this sorted.

**Comment by yoshihitoh** [comment]
@pimterry 
I found the root cause of the error, and fixed it!
Can I use your commit to upgrade Emscripten version? I cherry-picked the commit from the forked repository.
It's okay to cherry-pick my commits below and make this draft a ready PR if you don't mind.
- branch: [update/emscripten](https://github.com/yoshihitoh/zstd-codec/tree/update/emscripten)
- commits: https://github.com/yoshihitoh/zstd-codec/commits/update/emscripten

**Comment by pimterry** [comment]
Hi @yoshihitoh, thanks, that's really helpful!

I've cherry-picked your changes to update this, but I'm still having some issues. Using the bindings you committed, the tests pass great. When I rebuild though, I get a slightly different binding output to your update, and while many more tests pass, some still fail with:

```
 FAIL  lib/__tests__/zstd-stream.js
  ● Console

    console.log lib/zstd-codec-binding-wasm.js:8
      10
    console.warn lib/zstd-codec-binding-wasm.js:8
      10

  ● ZstdXXXTransform › should decompress zst file

    abort(10). Build with -s ASSERTIONS=1 for more info.



 FAIL  lib/__tests__/zstd-codec.js (5.473s)
  ● Console

    console.log lib/zstd-codec-binding-wasm.js:8
      10
    console.warn lib/zstd-codec-binding-wasm.js:8
      10
    console.log lib/zstd-codec-binding-wasm.js:8
      10
    console.warn lib/zstd-codec-binding-wasm.js:8
      10
    console.log lib/zstd-codec-binding-wasm.js:8
      10
    console.warn lib/zstd-codec-binding-wasm.js:8
      10
    console.log lib/zstd-codec-binding-wasm.js:8
      10
    console.warn lib/zstd-codec-binding-wasm.js:8
      10
    console.log lib/zstd-codec-binding-wasm.js:8
      10
    console.warn lib/zstd-codec-binding-wasm.js:8
      10
    console.log lib/zstd-codec-binding-wasm.js:8
      10
    console.warn lib/zstd-codec-binding-wasm.js:8
      10

  ● ZstdCodec.Simple › compressUsingDict › should compress data

    thrown: 5292360

    Error: 

      109 | 
      110 |     describe('compressUsingDict', () => {
    > 111 |         it('should compress data', done => {
          |         ^
      112 |             ZstdCodec.run((zstd) => {
      113 |                 const simple = new zstd.Simple();
      114 |                 const ZstdCompressionDict = zstd.Dict.Compression;

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.it (lib/__tests__/zstd-codec.js:111:9)
      at Suite.describe (lib/__tests__/zstd-codec.js:110:5)
      at Object.describe (lib/__tests__/zstd-codec.js:76:1)

  ● ZstdCodec.Streaming › compress() › should compress whole data

    abort(10). Build with -s ASSERTIONS=1 for more info.



  ● ZstdCodec.Streaming › compress() › should compress chunked data

    abort(10). Build with -s ASSERTIONS=1 for more info.



  ● ZstdCodec.Streaming › decompress() › should decompress whole data

    abort(10). Build with -s ASSERTIONS=1 for more info.



  ● ZstdCodec.Streaming › decompress() › should decompress chunked data

    abort(10). Build with -s ASSERTIONS=1 for more info.



  ● ZstdCodec.Streaming › compress/decompress using dict › should compre books using dict

    abort(10). Build with -s ASSERTIONS=1 for more info.



  ● ZstdCodec.Streaming › compress/decompress using dict › should compress chunked data

    abort(10). Build with -s ASSERTIONS=1 for more info.


Test Suites: 2 failed, 2 total
Tests:       8 failed, 4 passed, 12 total
Snapshots:   0 total
Time:        6.251s
Ran all test suites.
```

Any idea what I'm missing? I noticed that this PR on is the default `develop` branch, but your code is on the `master` branch. Should I be using that branch instead?

**Comment by yoshihitoh** [comment]
Hi @pimterry, thank you for trying the change!

> When I rebuild though, I get a slightly different binding output to your update, and while many more tests pass, some still fail with:

Hmm, it's wired. I tried removing the current binary, and then rebuilt them with modified `update_projects.sh` to enforce `--no-cache` option which generated literary same binary (git didn't detect differences.)
Since `update_projects.sh`uses Docker for building, I can't figure out any valid reason for this issue.

Would you please let me know your environment?
I built and tested this module with
- OS:macOS Big Sur 11.6 (Intel x86_64)
- Docker: Docker version 20.10.8, build 3967b7d
- Node.js: v12.9.1
- yarn: 1.22.17

To push/attach the binaries you built (which fails on tests) will help me investigate this issue.

> Any idea what I'm missing? I noticed that this PR on is the default develop branch, but your code is on the master branch. Should I be using that branch instead?

Hmm, I think base-branch is not the problem, the differences `between` master and `develop` will not affect the build result. (but I  should  update master branch :)  )

**Comment by pimterry** [comment]
> Would you please let me know your environment?

I'm using:

* OS: Ubuntu 20.04.3 (Intel x86_64)
* Docker: 20.10.7
* Node: v14.17.0
* Yarn: v1.22.10

I've just done a fresh test by running:

* `docker system prune -fa` (to reset all Docker state completely)
* `git clone --recursive git@github.com:httptoolkit/zstd-codec.git`
* `cd zstd-codec`
* `git checkout fix-build`
* Replace `greadlink` with `readlink` (`greadlink` only works on Mac) in ./update-zstd-binding.sh
* `bash ./update-zstd-binding.sh`

That builds the Docker container from scratch successfully, and updates the built output with a bunch of changes (I've committed and pushed all the results here).

It's quite surprising that that results in different output. That said, for some reason the tests do now pass on my machine against this build! I think I might've installed the JS packages via npm, which may not have used the yarn lockfile, and it's possible that broke the tests? That shouldn't affect the emscripten build though.

Anyway: the tests do now seem to pass, but it's still odd that I see different build output from this, and I'd be very interested if you can work out why.

**Comment by yoshihitoh** [comment]
Hi @pimterry , sorry for the late response.
Umm, it's really wired... I could finish the test using the binary you built on 3 major platforms, Windows, Linux, and macOS without failure. Since I don't have bare-metal Linux machines, I installed Ubuntu 20.04.3 on a Hyper-V VM instance.

Would you please try the following steps to get further information?
1. add `-s ASSERTIONS=1` option to the linker option on [cpp/premake5.lua:169-170](https://github.com/httptoolkit/zstd-codec/blob/fix-build/cpp/premake5.lua#L169)
2. rebuilt the binary
    - `bash ./update-zstd-binding.sh`
3. run js test again
    - `cd js/`
    - `yarn run test` or `npm run test`

> That builds the Docker container from scratch successfully, and updates the built output with a bunch of changes (I've committed and pushed all the results here).

I think this is the reason why the binaries have differences. I used old docker image caches. Removing the images of Emscripten and zstd-codec brought different binaries, but it worked well on the test.

> I think I might've installed the JS packages via npm, which may not have used the yarn lockfile, and it's possible that broke the tests? That shouldn't affect the emscripten build though.

This module zstd-codec doesn't depend on any js libraries for runtime and using Node.js environment installed on Docker containers, so this is not the case I think.

**Comment by pimterry** [comment]
I think there's some confusion here, sorry! With the above build, the test _do_ pass for me. The tests aren't a problem now (my best guess is that before they were failing before due to JS libraries installed without Yarn - although the build doesn't use JS libraries, the tests do, and that could cause this).

My remaining confusion was just around why the build output was different to yours, not the test results.

> I used old docker image caches. Removing the images of Emscripten and zstd-codec brought different binaries, but it worked well on the test.

This could be an explanation of the different output. To confirm: if you rebuild with a totally clean cache, do you now get the same result I pushed above? If so, I think everything is good here :+1:.

I've just tested again with a fresh directory using the steps above, and rebuilding still produces the same output for me, which still passes the tests, so that's great from my point of view.

Let me know if the wasm output is consistent for you now, and then I'll clean up the history here a little, we can get this merged, and I can look into fixing #214 on top.

**Comment by yoshihitoh** [comment]
> I think there's some confusion here, sorry! With the above build, the test do pass for me. 

Okay! I'm happy to hear that the binaries your built passed the tests successfully :)

>  To confirm: if you rebuild with a totally clean cache, do you now get the same result I pushed above? If so, I think everything is good here 👍.

Umm, I don't know why, but it made different outputs. I mean, git detected differences on those binaries. As far as I noticed, some variables/functions have been assigned different names by the closure compiler. I think these differences are not important in this case, Emscripten is a reliable toolchain to produce js/wasm binaries from c++ sources.

I think we can merge this PR now!

**Comment by pimterry** [comment]
@yoshihitoh I've merged the codec binding update commits, and added separate commits for three small fixes:

* A fix so that the build script works with both greadlink and readlink, so it can be used on both Linux & Mac
* Quotes around paths in the build script, so it works in paths with spaces
* Added a browserify dev dependency, which was implicitly used in the JS package scripts (the `build-local` script uses it, but it wasn't actually listed as a dependency)

If you're happy with everything here then I think it's ready to merge.

**Review by yoshihitoh — APPROVED** [review]
@pimterry 
Thank you for making improvements on scripts!
Looks good to me!

**Pull request merged**
